GET http://localhost:8000/users

###
GET http://localhost:8000/users/FrS1ifV8B8cvsP3F6jkuw

###
POST http://localhost:8000/users
content-type: application/json

{
    "firstName":"Namuunaa",
    "lastName": "Backend",
    "birthDate" : "1998-07-11",
    "email": "temuulen.m@pinecone.mn",
    "phone": "96667432",
    "password": "",
    "imageUrl": ""
}

###
DELETE http://localhost:8000/users/ZILSYCBnLaRQtQStdNScF

###
put http://localhost:8000/users/0n7eGqULwBtCIv-xpXlgn
content-type: application/json

{
    "firstName":"dulguun2",
    "lastName": "Backend",
    "birthDate" : "1998-07-11",
    "email": "temuulen.m@pinecone.mn",
    "phone": "99978722",
    "password": "",
    "imageUrl": ""
}
